Repository CSC207-UofT/course-project-bug-makers, pull requests merged in 2021-12, with the labels that each got.

#91 [Kuan Pang] Bug fixed and accessibility improvement
  src/main/java/com/courseApp/driver/cmdline/commands/QuitSession.java
  src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/CreateNewCourse.java
  src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/CreateNewInst.java
  src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/CreateNewUserReview.java
  src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/DeleteUserReview.java
  src/main/java/com/courseApp/driver/cmdline/commands/ReviewServiceCommand/EditUserReview.java
  src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
  src/main/java/com/courseApp/reviewService/ReviewServiceController.java
  src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
  src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
  teamDocumentation/cmdDocumentation.md
Labels: documentation, enhancement

#93 Bug fixed and Test Case implemented
  src/main/java/com/courseApp/reviewService/ReviewRequestProcessor.java
  src/test/java/com/courseApp/reviewService/ReviewRequestProcessorTest.java
  src/test/java/com/courseApp/reviewService/ReviewServiceControllerTest.java
Labels: enhancement

#95 [Kuan Pang] Phase 2 doc updated, test cases updated
  phase2/designdocument.assets/Adapter.png
  phase2/designdocument.assets/DDRefactoringCalendar
  phase2/designdocument.assets/courseAppUML.png
  phase2/designdocument.assets/decoratordiagram.png
  phase2/designdocument.assets/factoryMethodGraph.png
  phase2/designdocument.assets/myCourseAppIntrop1.png
  phase2/designdocument.assets/p1ca.jpg
  phase2/designdocument.assets/p1demo.jpeg
  phase2/designdocument.assets/readmedemo.gif
  phase2/designdocument.assets/reviewca.png
  phase2/designdocument.assets/reviewdemo.gif
  phase2/designdocument.assets/systemdesign.png
  phase2/designdocument.assets/webdemo.gif
  phase2/designdocument.md
  src/main/java/com/courseApp/courseService/CourseServiceController.java
  src/test/java/com/courseApp/courseService/CourseServiceControllerTest.java
Labels: documentation, enhancement

#99 Completed Accessibility Report
  gradle/wrapper/gradle-wrapper.jar
  phase2/designdocument.assets/AchiDiagram.png
  phase2/designdocument.assets/courseApp.uml
  phase2/designdocument.md
Labels: documentation

#102 [Phase 2 FINAL PR] Link fixed.
  README.md
  phase2/designdocument.md
Labels: bug
